---
title: "Rebecca_Extensions"
author: "rebecca"
date: "November 1, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r mouse, fig.width = 8, fig.height = 8}
library(ggmap)
library(readxl)
library(ggpolypath)
library(viridis)
library(dplyr)
library(tidyr)

source("../sampledata.R")

example_data <- test_data %>% 
  select(drug, dosage, dose_int, level, PLA, SLU, SLE) %>% 
  unite(drug_dosing, drug, dosage, dose_int, sep = "-") %>% 
  filter(level == "Cmax") %>% 
  gather(PLA:SLE, key = "ELEMENT", value = concentration) %>% 
  mutate(ELEMENT = factor(ELEMENT, levels = c("PLA", "SLU", "SLE"),
                          labels = c("MOUSE", "LUNGS", "LESION")),
         ELEMENT = as.character(ELEMENT))

mouse <- read_excel('../sample_data/MouseCoord.xlsx') %>% 
  left_join(example_data, by = "ELEMENT")

ggplot(data = mouse, aes(mapping = TRUE, x = X, y = Y, group = HOLE, 
                         fill = concentration)) +
  geom_polypath(rule = "evenodd") +
  geom_path(colour = "black", size = .5) +
  theme_void() +
  theme(legend.position = 'top') +
  coord_fixed()  +
  scale_fill_viridis(option = "magma") + 
  facet_wrap(~ drug_dosing)

```


```{r lesion}
lesion <- read_excel('../sample_data/LesionCoord.xlsx') 
ggplot(data = lesion, aes(mapping = TRUE, x = X, y = Y, group = HOLE, fill = AREA)) +
  geom_polypath(rule = "evenodd") +
  geom_path(colour = "black", size = .5) +
  theme_void() +
  theme(legend.position = 'none', panel.background = element_rect(fill = "darkgray")) +
  coord_fixed(ratio = 1, xlim = c(-12,12), ylim = c(-12,12)) +
  scale_fill_viridis(discrete = TRUE, option = "magma") 

```
