---
title: "Colleen_heirarchical"
author: "Colleen Brents"
date: "November 8, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#colleen's to do
+ help files for 'hclust'
[hclust](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/hclust.html)
rplot (alluvial diagrams stuff)
+ might want to use mutate_all to scale all columns before run `as.matrix` 
+ ggraph and geomnet 
[ggraph](https://cran.r-project.org/web/packages/ggraph/index.html) 

reference example_ggraph 
#split by chemical and biological markers 
[tutorial](http://www.sthda.com/english/articles/28-hierarchical-clustering-essentials/92-visualizing-dendrograms-ultimate-guide/)

```{r libraries and raw data}
library(readr)
library(dplyr)
library(tidyr) #unite
library(ggraph)
library(tibble)
library(dendextend)
library(ggdendro)
test_data <- read_csv(paste0("https://raw.githubusercontent.com/KatieKey/input_output_shiny_group/",
                             "master/CSV_Files/efficacy_summary.csv"))
```

```{r simple cluster diagram }
test_data_dend <- test_data %>% 
  tidyr::unite(drugz, drug:level, sep = "_") %>% #combine identifying data into one column, 
  remove_rownames %>% 
  column_to_rownames (var = "drugz") %>%  #make drugz row name 
  select(PLA:MacUptake, -ELU, -ESP) %>%  #remove efficacy 
  mutate_each_(funs(scale(.) %>% as.vector),
               vars = c("PLA", "ULU", "RIM", "OCS", "ICS", "SLU", "SLE", "cLogP", "huPPB","muPPB",
               "MIC_Erdman", "MICserumErd", "MIC_Rv", "Caseum_binding", "MacUptake")) %>% 
  rename(plasma = PLA,
         uninvolved_lung = ULU,
         outer_caseum = OCS,
         inner_caseum = ICS,
         standard_lung = SLU,
         standard_lesion = SLE,
         macrophage_uptake = MacUptake,
         human_binding_plasma =huPPB,
         mouse_binding_plasma = muPPB) %>% 
  as.matrix() %>% 
  t() %>% #transpose 
  dist() %>% 
  hclust() %>% 
  as.dendrogram(horiz = TRUE, hang = .1) 

ggdendrogram(test_data_dend, 
             segments = TRUE,
             rotate = TRUE, 
             labels = TRUE,
             leaf_labels = TRUE,
             size = 2,
             theme_dendro = TRUE)  +
  labs(title = "Comparison by test") +
  
#other plot method 
# plot(xlab = "",
#      ylab = "",
#      main = "Across Drug Measurements",
#      horiz = TRUE,
#      axes = FALSE)
#   par(cex = 0.6, mar=c(9,11,7,7)) %>% #cex magnifies text; mar does axis
#   par(cex = 0.6)
#add column 
# invivo_bio<- c("cLogP", "huPPB","muPPB", "MIC_Erdman", "MICserumErd", "MIC_Rv","Caseum_binding", "MacUptake") 
# invitro_chem<- c("PLA", "ULU", "RIM", "OCS", "ICS", "SLU", "SLE")
```

```{r make formatted dendogram by drug  }
test_data_dend2 <- test_data %>% 
  tidyr::unite(drugdetail, drug:level, sep = "_") %>% #combine identifying data into one column, 
  mutate_each_(funs(scale(.) %>% as.vector),
               vars = c("PLA", "ULU", "RIM", "OCS", "ICS", "SLU", "SLE", "cLogP", "huPPB","muPPB",
               "MIC_Erdman", "MICserumErd", "MIC_Rv", "Caseum_binding", "MacUptake")) %>% #scales
  select(drugdetail, PLA:MacUptake, -ELU, -ESP) %>%  #remove efficacy 
  tibble::column_to_rownames (var = "drugdetail") %>%  #make drugdetail leaf name!  
  dist() %>% 
  hclust() %>%  #can change method 
  as.dendrogram(horiz = TRUE, hang = .1) 

ggdendrogram(test_data_dend2, 
             segments = TRUE,
             rotate = TRUE, 
             labels = TRUE,
             #leaf_labels = TRUE,
             size = 2,
             theme_dendro = TRUE)  +
  labs(title = "Comparison by drug, dose, dose-int, and level") +
  theme(axis.title.x = element_blank(),
         axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
  
```
resource for color coding leaves [here](https://stackoverflow.com/questions/31117849/how-to-color-a-dendrograms-labels-according-to-defined-groups-in-r)
learn about extendogram [here](https://cran.r-project.org/web/packages/dendextend/vignettes/introduction.html)
also [here](https://rpubs.com/gaston/dendrograms) 

```{r sort by in vivo or in vitro IN PROGRESS }
test_data <- read_csv(paste0("https://raw.githubusercontent.com/KatieKey/input_output_shiny_group/",
                             "master/CSV_Files/efficacy_summary.csv"))

sortr <- test_data %>% 
  tidyr::unite(drugdetail, drug:level, sep = "_") %>% #combine identifying data into one column, 
  remove_rownames %>% 
  tibble::column_to_rownames (var = "drugdetail") %>%  #make drugdetail row name , but doesn' showup 
  select(PLA:MacUptake, -ELU, -ESP) %>%  #remove efficacy 
  mutate_each_(funs(scale(.) %>% as.vector),
               vars = c("PLA", "ULU", "RIM", "OCS", "ICS", "SLU", "SLE", "cLogP", "huPPB","muPPB",
               "MIC_Erdman", "MICserumErd", "MIC_Rv", "Caseum_binding", "MacUptake")) %>% #scales 
  as.matrix() %>% 
  t() %>%  
  as.data.frame() %>% 
  tibble::rownames_to_column(var = "drugtype") #makes drugtype new rowname, but dont see 

sortr$type <- ifelse(sortr$drugtype %in% c("cLogP", "huPPB","muPPB", "MIC_Erdman", "MICserumErd", "MIC_Rv","Caseum_binding", "MacUptake"), "invivo", "invitro") #made new column 
df<- sortr %>% 
 # select(drugtype,type, DRUG1_50_BID_Cmax:DRUG11_100_QD_Trough) %>% #if include type 
  select(drugtype,type, V1:V21) %>% #lost column names 
  dist() %>% 
  hclust() %>% 
  as.dendrogram(horiz = TRUE, hang = .1) %>% 
plot(xlab = "",
     ylab = "",
     main = "Across Drug Measurements",
     horiz = TRUE,
     axes = FALSE)
  par(cex = 0.6, mar=c(9,11,7,7)) %>% #cex magnifies text; mar does axis
  par(cex = 0.6) 

#how to make dendogram and color according to column (invivo or invitro)
  
ggdendrogram(df, 
             segments = TRUE,
             rotate = TRUE, 
             labels = TRUE,
             #leaf_labels = TRUE,
             size = 2,
             theme_dendro = TRUE)  +
  labs(title = "Comparison by test") +
  theme(axis.title.x = element_blank(),
         axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

```



